### ISSUE TITLE
Failure to compile

### ISSUE THREAD

**Issue by yangwukaidi** [EwenBurban/RIDGE#1]
Hi
Thank you for sharing the software.
I recently had a problem executing _bash configure.sh_
I looked at the process, found that the problem was caused by "FactoMineR", "factoextra" was not installed successfully.
Later, I further found that the two R packages failed because "estimability", "emmeans“, “nloptr”, ”lme4“, ”pbkrtest“, ”car“ did not install successfully. 
How can I better solve this problem, so that the software can be successfully installed.
Looking forward to your reply！

**Comment by yangwukaidi** [comment]
Hi
I solved this problem by changing "From: r-base:4.1.0" to "From: r-base:4.3.1" in R_visual.def.  Is this feasible?
And I found that "--max-threads=100" might be changed to "--jobs=100" in RIDGE.sh.
Another question is, what should the contents of the popfile.csv look like when the number of individuals of my two species is not equal?
I look forward to your help.

**Comment by EwenBurban** [comment]
Hi,
Thanks for your interest for RIDGE. 
Changing r-base version is completely feasible and as packages for 4.1.0 version aren't maintain, i'll update R_visual.def with the new version on R asap. 
About "--max-threads" and "--jobs", actually in launch_param.sh you have to specify the number of jobs you want to launch in parallel. For "--max-threads" i'll probably remove it as it's useless.
Concerning  popfile.csv, as mentioned in the user_manual, you just have to fill with NA in order to have the same number of individuals in both species (see 1.3.3 Popfile from user_manual.pdf).
Thanks for your report, it'll help me to improve RIDGE.
Best.

**Comment by EwenBurban** [comment]
Can I close the issue ?

**Comment by yangwukaidi** [comment]
Well. Thank you for your reply.
